### ISSUE TITLE
Video Walkthrough for Font-specific features

### ISSUE THREAD

**Issue by vilav** [nazikus/rhythmic-grids#4]
Hi 

I'm not a designer but I'd love to understand how to get the most out of concordia. Any chance you can do  a video walkthrough going through the typography options available with the tool?

Thanks!

**Comment by ArsenBatyuchok** [comment]
@rsokolovski

**Comment by ArsenBatyuchok** [comment]
Hi @vilav , did you have a chance to look at our [Medium](https://voices.basedesign.com/make-modular-grids-in-seconds-e2eeee95aa4f) article? It should be enough to understand how it helps to choose a legible font.
